### ISSUE TITLE
Footer is shifted left by 25rem when there's no sidebar

### ISSUE THREAD

**Issue by ash-rc** [codeforamerica/honeycrisp-gem#236] opened 2021-01-26 22:10 UTC
[This commit](https://github.com/codeforamerica/honeycrisp-gem/commit/f5d53fc1e6a95688cc8ecb678f6823408f3d276f#diff-9a256c1ba8c8d7ada3f8e0dbbc28dbc5b1c0f85bc5f2c3233056a7ecbfef3019R199) introduced a variable that pushes the footer over by 25rem to make space for the sidebar. 

However its being applied universally, shifting the footer over all the time! 

Here's what the GCF footer looks like with the current footer styling 

<img width="1440" alt="Screen Shot 2021-01-26 at 2 09 39 PM" src="https://user-images.githubusercontent.com/5702758/105912315-23086d80-5fe0-11eb-926a-2d8e3a6e812f.png">

**Comment by racheledelman** [comment] 2021-01-26 22:29
seems bad! the default should definitely assume no sidebar.

**Comment by lkogler** [comment] 2021-01-26 23:53
Yup, this is bad and we should fix it! But I'm going to close this since it is a duplicate of #212

**Closed by lkogler** 2021-01-26 23:53 UTC
Labels: bug
